name: Publish

on:
  push:
    branches:
      - docs
  workflow_call:
    secrets:
      BUILDER:
        required: true
  workflow_dispatch:

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ secrets.BUILDER }}/dispatches \
            -d '{"event_type":"deploy", "client_payload":{"branch": "${{ github.ref }}"}}'
